### ISSUE TITLE
Error when signing up with email

### ISSUE THREAD

**Issue by Vanclief** [rhomeister/alphagrader#12]
**Expected behavior:**
A new user can sign up through the sign up page and receive a confirmation email.

**Observed behavior:**
A new user does not receive a confirmation email. Application logs: 

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Steps to reproduce:**
1. Go to https://www.alphagrader.com/users/sign_up
2. Sign up with email
3. Fill the form
4. Click on Submit
5. No profit

**Comment by rhomeister** [comment]
Email provider stopped working. Switching to new one.

**Comment by rhomeister** [comment]
Fixed.
