### ISSUE TITLE
Request: Support for Adding Regex to Output

### ISSUE THREAD

**Issue by Vanclief** [rhomeister/alphagrader#2]
- Allow instructors to add (Print anything option)
- Allow instructors to add specific Regex

**Comment by rhomeister** [comment]
What is the purpose of the first option? Could you give an example?

**Comment by Vanclief** [comment]
Its like a "Don't care" maybe in your team assignment you specify that students must ask the user for input. So students can do it in different ways:

* Please give me the input
* Insert input
* You bastard give me the input

All of those should be ok. (Maybe the bastard one not so much)

**Comment by rhomeister** [comment]
Closed through #3 and installed.
