### ISSUE TITLE
Problem submitting C files from Zip

### ISSUE THREAD

**Issue by Vanclief** [rhomeister/alphagrader#7]
**Expected result:** When submitting a C file as a zip following the [guidelines](https://github.com/rhomeister/alphagrader/wiki/Expected-Output-Test-using-C) Alphagrader runs the tests.

**Outcome:** Alphagrader fails to run the file with the following output:

```
gcc: error: program: No such file or directory
./run: 3: ./run: ./program: not found
```

**Comment by rhomeister** [comment]
Do you have the zip file that fails?

**Comment by Vanclief** [comment]
Found the error, my run script was the problem, not alphagrader. Documentation is incorrect: https://github.com/rhomeister/alphagrader/wiki/Expected-Output-Test-using-C

This

```
#!/bin/sh
gcc program.c -out program
./program
```

Should be

```
#!/bin/sh
gcc program.c -o program
./program
```

My bad for copying and pasting without even reading 🥇
